- name: test
  debug: msg="curl -sfL https://get.k3s.io | K3S_TOKEN={{ token }} K3S_URL=https://192.168.2.200:6443 K3S_NODE_NAME={{ inventory_hostname }} sh -"
- name: k3s Node connection
  become: yes
  become_method: sudo
  ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_TOKEN={{ token }} K3S_URL=https://192.168.2.200:6443 K3S_NODE_NAME={{ inventory_hostname }} sh -
    


