- name: Validate the sudoers file before saving
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo   ALL='
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL '
    validate: /usr/sbin/visudo -cf %s

- name: Fetch k3sup setup
  get_url:
    url: https://get.k3sup.dev
    dest: /usr/local/bin/getk3sup.sh
    mode: 0755
  become: yes
  register: fetchgetk3sup

- name: Install k3sup binary
  when: fetchgetk3sup is succeeded
  command: /usr/local/bin/getk3sup.sh
  become: yes
  register: installk3sup

- name: if this file does not exist, let me know, but continue
  debug: msg="k3sup join --ip {{ ansible_ssh_host }} --server-ip {{ Goddessipaddy }} --user {{ inventory_hostname }}"

- name: install k3 on nodes.
  become: yes
  become_method: sudo
  ansible.builtin.shell: k3sup join --ip {{ ansible_ssh_host }} --server-ip {{ Goddessipaddy }} --user {{ inventory_hostname }}

- name: Validate the sudoers file before saving
  become: yes
  become_method: sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo   ALL='
    line: '%sudo   ALL=(ALL:ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
    


