- name: install k3 on nodes.
  become: yes
  become_method: sudo
  ansible.builtin.command: curl -sfL https://get.k3s.io | K3S_TOKEN="{{ k3smastertoken }}" K3S_URL="https://Goddess:6443" K3S_NODE_NAME="{{ inventory_hostname }}" sh - 
