---
- hosts: command
  vars:
    inventory_hostname: Goddess
    ansible_sudo_pass: "{{ lookup('password', 'passwords/' + inventory_hostname) }}"
  user: astra
  roles:
    - command
    - common
  
- hosts: dragons
  vars:
    inventory_hostname: Dragons
    ansible_sudo_pass: "{{ lookup('password', 'passwords/' + inventory_hostname) }}"
  user: dragon
  roles:
    - common

#- hosts: monitoring_server 
#  user: pi
#  roles:
#    - monitoring_server 
