---
- hosts: command
  vars:
    ansible_sudo_pass="{{ lookup('passwordstore', inventory_hostname) }}"
  user: astra
  roles:
    - command
    - common
  
- hosts: dragons
  vars:
    ansible_sudo_pass: "{{ lookup('passwordstore', inventory_hostname) }}"
  user: dragon
  roles:
    - common

#- hosts: monitoring_server 
#  user: pi
#  roles:
#    - monitoring_server 
