---
- hosts: command
  user: astra
  roles:
    - command
    - common
    
- hosts: dragons
  user: dragon
  roles:
    - common

#- hosts: monitoring_server 
#  user: pi
#  roles:
#    - monitoring_server 
