---
- name: 'Update and upgrade apt packages'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  vars:
    ansible_sudo_pass: "{{ lookup('passwordstore', 'inventory_hostname') }}"
- name: 'Install packages'
  become: yes
  apt:
    pkg:
      - python3-pip
      - git
      - nano
    vars:
    ansible_sudo_pass: "{{ lookup('passwordstore', 'inventory_hostname') }}"
      
